version: '3.9'

services:
  comm_server:
    image: solidproject/community-server:latest
    container_name: comm_server
    ports:
      - "3000:3000"
    volumes:
      - ./servers/css/data:/data
      - ./servers/css/config:/config
    command: >
      --port 3000
    restart: unless-stopped

  solid-cinema-vue:
    build:
      context: ./my-apps/solid-cinema-vue
    image: solid-cinema-vue
    ports:
      - "8081:80"
  solid-file-manager:
    container_name: solid-file-manager
    build:
      context: .
      dockerfile: third-party-apps/docker/Dockerfile.solid-file-manager
    ports:
      - "8082:3001"
    environment:
      - HOST=0.0.0.0

  media-kraken:
    container_name: media-kraken
    build:
      context: .
      dockerfile: third-party-apps/docker/Dockerfile.media-kraken
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
    depends_on:
      - solid-file-manager


networks:
  default:
    name: solid-network
