version: '3.9'

services:
  comm_server:
    image: solidproject/community-server:latest
    container_name: comm_server
    ports:
      - "3000:3000"
    volumes:
      - ./servers/css/data:/data
      - ./servers/css/config:/config
    command: >
      --port 3000
    restart: unless-stopped

  solid-cinema-vue:
    build:
      context: ./my-apps/solid-cinema-vue
    image: solid-cinema-vue
    ports:
      - "8081:80"


networks:
  default:
    name: solid-network
